embed_assets: datauri

javascripts:
  base:
    - public/javascripts/i18n/pt-BR.js
    - public/javascripts/jquery.js
    - public/javascripts/jquery.tmpl.js
    - public/javascripts/rails.js
    - public/javascripts/jquery.tools.min.js
    - public/javascripts/jquery-ui.min.js
    - public/javascripts/jquery.notifyBar.js
    - public/javascripts/jquery.hotkeys.js
    - public/javascripts/jquery.colorbox-min.js
    - public/javascripts/jquery.poshytip.js
    - public/javascripts/jquery.form.js
    - public/javascripts/jquery.remotipart.js
    - public/javascripts/utils.js
    - public/javascripts/autocompleteBox.js
    - public/javascripts/editor.js
    - public/javascripts/application.js
    - public/javascripts/topbar.js
    - public/javascripts/modules/welcome.js
    - public/javascripts/modules/follow_link.js
    - public/javascripts/modules/ignore_link.js
    - public/javascripts/modules/cookies.js
    - public/javascripts/modules/inline_edition.js
    - public/javascripts/modules/votes.js
    - public/javascripts/modules/import_contacts.js
    - public/javascripts/modules/topic_tooltip.js
    - public/javascripts/modules/user_suggestions.js
    - public/javascripts/modules/math_preview.js
    - public/javascripts/modules/share_content.js
    - public/javascripts/modules/inline_autocomplete.js
  landing:
    - public/javascripts/modules/landing.js
  suggestions:
    - public/javascripts/modules/suggestions.js
  content_edit:
    - public/javascripts/modules/single/question.js
  signup_follow:
    - public/javascripts/modules/signup_follow.js
  new_question:
    - public/javascripts/modules/topic_autocomplete.js
    - public/javascripts/modules/question_autocomplete.js
    - public/javascripts/modules/new_question.js
  new_question_as_search:
    - public/javascripts/modules/topic_autocomplete.js
    - public/javascripts/modules/new_question_as_search.js
  new_question_list:
    - public/javascripts/modules/topic_autocomplete.js
    - public/javascripts/modules/new_question_list.js
  show_question:
    - public/javascripts/modules/topic_autocomplete.js
    - public/javascripts/modules/show_question.js
  show_question_list:
    - public/javascripts/modules/topic_autocomplete.js
    - public/javascripts/modules/show_question_list.js
  external_accounts:
    - public/javascripts/modules/dac_external_account.js
  topics_email_subscription:
    - public/javascripts/modules/email_subscription.js
  student_invitation:
    - public/javascripts/modules/invite_course.js
  request_answer:
    - public/javascripts/modules/request_answer.js
  print:
    - public/javascripts/modules/print.js

stylesheets:
  base:
    - public/stylesheets/jquery-ui.css
    - public/stylesheets/compiled/application.css
    - public/stylesheets/autocomplete.css
    - public/stylesheets/colorbox.css
    - public/stylesheets/compiled/themes/plain/style.css
    - public/stylesheets/welcome.css
    - public/stylesheets/tip-twitter.css
  landing:
    - public/stylesheets/autocomplete_landing.css
    - public/stylesheets/compiled/landing.css
    - public/stylesheets/tip-twitter.css
  embedded:
    - public/stylesheets/embedded.css
  question_list_print:
    - public/stylesheets/compiled/question_list_print.css
